name = "portfolio"
main = "functions/_middleware.ts"
compatibility_date = "2025-01-01"

[build]
command = "npm install"
cwd = "./functions"
watch_paths = ["src/**/*.ts"]

[env.production]
routes = [
  { pattern = "muni-no.net", zone_name = "muni-no.net" }
]

